version: '3'

services:
  mysqlos:
    image: mysql:5.6
    volumes:
      - mysql_new:/var/lib/msql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: sumanto
      MYSQL_PASSWORD: passwod
      MYSQL_DATABASE: mydb

  joomlaos:
    image: joomla:3.9-php7.2-apache
    restart: always
    depends_on:
      - mysqlos
    ports:
      - 8081:8081
    environment:
      JOOMLA_DB_HOST: mysql:3306
      JOOMLA_DB_USER: sumanto
      JOOMLA_DB_PASSWORD: password
      JOOMLA_DB_NAME: mydb
    volumes:
      - jm_new:/var/www/html

volumes:
  jm_new:
  mysql_new:

